### ISSUE TITLE
Use ReSpec for writing the documentation

### ISSUE THREAD

**Issue by ahankinson** [OCFL/spec#13]
n/t

**Comment by zimeon** [comment]
Notes from experience with ReSpec in https://github.com/fcrepo/fcrepo-specification 
  * Include local copy of respec-w3c-common.js and reference that with relative link so that one can work on planes without network
  *  Example travis setup in https://github.com/fcrepo/fcrepo-specification/blob/master/.travis.yml -- we have a line length limit check which is just a matter of style but I think helpful

**Comment by awoods** [comment]
@ahankinson : Here is a [pull-request](https://github.com/OCFL/spec/pull/15) that brings in the TOC and logo.
The logo required reverting to an earlier version of the respec-w3c-common.js library.

**Comment by awoods** [comment]
Suggest closing this ticket, as we are well on our way to RSpec.
