### ISSUE TITLE
Version directory names -- leading zeros (and if so how many), or not?

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#2]
From draft document which proposed 4 digits `v0001` etc.:

> @zimeon: What happens with 10,000th version? Need to define whether that is illegal (and debate number of digits) or there is extension to v10000 to deal with possible edge case (as in e.g. https://github.com/ndlib/bendo/blame/master/architecture/bundle.md#L16-L18 )

> @awoods: +1

> @julianmorley: It's a concern, but in the many years that Stanford has been using this format, the average version # in our repo (out of 1.5MM objects) is 2.5, and the highest version number is 20.

> @neilsjefferies: Why not just drop the leading zeros, the maximum version is thus limited by filesystem naming.

> @zimeon: I agree that dropping the leading zeros is probably the cleanest solution -- the combination of manually looking at the directory structure AND having > 9 versions very often seems like a real edge case

> @ahankinson: The risk with dropping the leading zeroes is ASCIIbetical sorting -- v1, v10, v100, v2, v20, v200, etc.. I agree that dropping the zeroes has significant advantages, so I'm ok with it, but it would be good to recognise the disadvantages as well.

> @rosy1280: +1 for some type of ASCIIbetical sorting. what would be the advantage of having all those 0s rather than just a single 0. i would imagine there is some, but i can not think of one (or remember why it was done that way although i can remember being told why...)

**Comment by ahankinson** [comment]
For the 'why': In order to get systems that sort by ASCII character number to sort "naturally" you need to left-pad to the number of zeroes for the largest number you want to sort accurately. So padding with five zeroes gives us 99,999 versions that will sort correctly. 

There are ways to get an OS to sort directories naturally (`ls -v` in linux; `ls -1 | sort -n` in OS X), and the GUIs on most systems do it by default, so I don't think it's critical if we keep or drop the zeroes.

**Comment by zimeon** [comment]
I favor no leading zeros because it is simpler and creates no arbitrary limit or behavior switch

**Comment by julianmorley** [comment]
Backwards compatibility with Moab would be 5-digit versions. FWIW after 5 years and 1.5 million objects, our highest version number is 20.

**Comment by julianmorley** [comment]
Can we say that versions are 'v'+integer, with a 'may be zero-padded' clause? That way OCFL can be neater, but Moab is still compliant.

**Comment by zimeon** [comment]
@julianmorley -- That is an interesting possibility. There would be no ambiguity in your definition for interpreting an OCFL object, but some additional errors cases and things to think about in client libraries. Issues I can think of:
  * An OCFL object that contains multiple directories that have the same version number expressed differently is INVALID (e.g. `v1`, `v01`, `v00001` together is INVALID)
  * If a OCFL processor is asked to add a version to an OCFL object, it would have to decide whether to follow its own convention or the convention in the object (or whether that isn't possible because the convention used is mixed, e.g. complete the series `v1`, `v02`, `v0003` but not with `v0000004` ;-) )
  * Should references to files in other versions use the actual directory name or the normalized version? Probably the former but that would mean that processors have to work with both the actual version number and the directory name for different tasks

**Comment by neilsjefferies** [comment]
How about:
- As @zimeon said...OCFL objects must be versioned consistently or be invalid.
- If versioning is fixed length padded then it must start with a zero. This reduces the number of versions in these cases by one order of magnitude which won't affect existing MOAB material according to @julianmorley's stats. Thus with five places we support v00001 to v09999. This is easy to pick up when parsing an object and we can follow suit for new versions. 
- The first version of an object thus defines the subsequent naming convention unambiguously.
- Otherwise we use v+unpadded integer and have versions limited by filesystem naming.
- References should use actual directory name.

**Comment by awoods** [comment]
The extended flexibility with additional requirements seems reasonable. Can we agree on the points above and flag this as text to be moved into the spec?
