### ISSUE TITLE
Allow for user-determined checksum algorithms 

### ISSUE THREAD

**Issue by SibylSchaefer** [OCFL/spec#21]
Currently, SHA-512 is used only in a minority of preservation settings as the fixity checking algorithm (see the 2017 [NDSA Fixty Survey Report](https://ndsa.org/documents/Report_2017NDSAFixitySurvery.pdf), p22 -23). Requiring SHA-512 may be a cumbersome barrier for those who want to adopt OCFL.

**Comment by ahankinson** [comment]
Thanks, Sibyl! And especially for the link to the survey report -- very interesting!

A brief summary of the discussions on this issue to date, since they don't seem to be captured anywhere:

The choice of SHA-512 should be viewed as an alternate to SHA-256, which we discussed in issue #8 .  It turns out that SHA-512 is faster to compute, so would be less of a burden.

In the first community call we discussed the choice of Moab to support both MD5 and SHA1. A comment was made by someone on that call that they wished it just supported a single hashing algorithm, for simplicity of implementation and checking.

One of the principle functions of the hashing algorithm is to provide content-addressable storage and de-duplication. It may also be used as a fixity check, but the choice of hashing algorithm should be understand in light of providing both functions.

MD5 and SHA1 are widely used, but are not necessarily future-proof as they are both now cryptographically [insecure](https://shattered.io).

Someone suggested to me that we adopt Multihash values: https://github.com/multiformats/multihash. I'm a bit wary of this as it is an external dependency to our work. 

We could allow specification of the hash algorithm on the object level, but we won't be able to mix hash types; you can't have half your hashes as MD5, and the other half as SHA1.

**Comment by ahankinson** [comment]
(My personal view is that we should use OCFL to drive best-practice adoption, which would suggest the use of SHA-512 by default, but we may be able to support SHA1 and MD5 for 'legacy' content.)

**Comment by julianmorley** [comment]
I concur with @ahankinson - sha512 by default, with an option to 'downgrade' on a per-object basis to another algo (or upgrade, as the spec evolves). 

And I think it was me who was lamenting about the many checksums in Moab (and if it wasn't, I'd add my lament anyway). The reasoning for Moab was that it provides an additional defense against checksum collisions and potential malicious manipulation of files that, after manipulation, produce the same checksum but are clearly no longer the same content. It also provides a more seamless migration of existing content to new algorithms - just drop the oldest and add the new one, whilst maintaining the 3rd algorithm as a common bridge. The viability and necessity of that approach is definitely open for discussion.

**Comment by ahankinson** [comment]
We decided that:
 - SHA-512 is the recommended default for OCFL objects v1
 - Other checksums can be supported, we store them in the inventory file on the key `hashAlgorithm`, e.g., `hashAlgorithm: sha512`
 - SHA-512 will be written as a SHOULD in the spec, and thus any other values will raise a warning in validation. 
 - Validators should support a restricted list of algorithms, e.g.,crc, md5, sha1, sha256, sha512
 - The inventory hash should match the hashing algorithm in the inventory file, e.g., `inventory.jsonld.md5` would contain an `inventory.jsonld` hash for md5

**Comment by zimeon** [comment]
At the very least it seems that the spec has to maintain or refer to a set of strings that identify different algorithms and the way the output is serialized, without that it isn't even possible to tell whether something is supported or not. I suspect we don't want to maintain this so perhaps adopting the [IANA registry](https://www.iana.org/assignments/http-dig-alg/http-dig-alg.xhtml) for definitions would make sense  (other options would be the [multihash table](https://github.com/multiformats/multihash/blob/master/hashtable.csv) or the [LC registry](http://id.loc.gov/vocabulary/preservation/cryptographicHashFunctions.html)).

Having said this, I wonder whether we should question the conflation of fixity and structural use in OCFL. As @SibylSchaefer points out, most objects currently being preserved use checksums other than sha-512, so it may be helpful to allow OCFL to use other formats for fixity verification. However, there are currently zero real OCFL objects in existence so I'm not sure it would be a problem to require the use of sha-512 for object structure _if_ those functions were split (by, for example, allowing additional digests for fixity purposes)

**Comment by zimeon** [comment]
Another (rather limited) set of hash algorithms is defined in [W3C TR Content Security Policy Level 2](https://www.w3.org/TR/CSP2/#source-list-syntax) -- but just `sha256` / `sha384` / `sha512` so likely not of use to us

**Comment by ahankinson** [comment]
Decision: Editors Meeting 2018-08-15 (and previous): We will definitely support multiple digest algorithms, with SHA-512 preferred default.
