### ISSUE TITLE
error in example versioned object

### ISSUE THREAD

**Issue by atomotic** [OCFL/spec#250]
according to the description of the following text i think that the structure reported here is incomplete or wrong 
https://ocfl.io/0.1/spec/#example-versioned-object
https://github.com/OCFL/spec/blob/master/0.1/spec/index.html#L895-L904

in v2 shouldn't be:
``` 
├── foo
|   └── bar.xml
```

**Comment by awoods** [comment]
Thanks, @atomotic !

**Comment by zimeon** [comment]
Agreed, thanks!

**Comment by edsu** [comment]
Was this actually fixed? I still seem to see the same problem live in the directory listing that precedes the JSON example at https://ocfl.io/0.1/spec/#example-versioned-object

```
    ├── v2    
    │   ├── inventory.json
    │   ├── inventory.json.sha512
    │   └── content
    │       ├── foo
    │       └── bar.xml
```

should be:

```
    ├── v2    
    │   ├── inventory.json
    │   ├── inventory.json.sha512
    │   └── content
    │       └── foo
    │           └── bar.xml
```

I may be mistaken, but it also seems like some of the digest values in `state` stanzas do not match up with digest values in the `fixity` stanza?

For example in `versions.v3.state`

```json
"ffccf6...62e": [ "image.tiff" ]
```

shouldn't that be:

```json
"b9c7cc...b49": [ "image.tiff" ]
```

Which raises another question for me of how you will know what fixity algorithm is being used in the version state, so that you can correctly look it up in the inventory? Shouldn't that be specified or mandated somehow?

Finally, just for the clarity in the example it would be useful if full or abbreviated fixity values were consistently used instead of mixing them together as they are currently.

**Comment by zimeon** [comment]
`/0.1/` is a fixed version, see https://ocfl.io/draft/spec/#example-versioned-object for the fixed one:

```
    ├── v2
    │   ├── inventory.json
    │   ├── inventory.json.sha512
    │   └── content
    │       └── foo
    │           └── bar.xml
```

The `fixity` block has `md5` and `sha1` additional fixity values. The `manifest` and `state` blocks use `sha512` as defined by the `digestAlgorithm` property.

We truncate only the very long `sha512` values but I think we do that consistently. Not sure whether it would help to truncate the others.

**Comment by edsu** [comment]
Oh I see the foo/bar.xml is fixed in the [published draft](https://ocfl.io/draft/spec/#example-versioned-object).

I also see now that the version digest values are looked up in the `manifest` not the `fixity` ... and that those match up just fine, and that the fixity algorithm is specified with `digestAlgorithm`

So never mind!
