### ISSUE TITLE
Clarification of object identifiers and URIs

### ISSUE THREAD

**Issue by peichman-umd** [OCFL/spec#312]
I had a question regarding OCFL objects and their ids, as described in the 0.2 spec. In both the Terminology section (https://ocfl.io/0.2/spec/#dfn-ocfl-object) and the OCFL Object spec section (https://ocfl.io/0.2/spec/#object-spec), the language describing the OCFL object's identifier suggest that it is always a URI:

> "A group of one or more content files and administrative information, that are together identified by a URI."

However, in the description of the object inventory (https://ocfl.io/0.2/spec/#inventory-structure), the `id` is not required to be a URI:

> "A unique identifier for the OCFL Object. This MUST be unique in the local context, and SHOULD be a URI [RFC3986]."

I was wondering what the reasoning behind making the requirement that an `id` be a URI a `SHOULD` instead of a `MUST`, given the earlier descriptions in the spec lead me to believe that an OCFL object would always be identified using a URI?

Furthermore, along with @awoods, I would suggest that either the terminology section (and intro text to section 3) should changed to something like "uniquely identified", or the `SHOULD` in the `id` definition in section 3.5.1 should be changed to a `MUST`.

My inclination is to promote the definition of `id` as a URI from a `SHOULD` to a `MUST`, in the absence of any compelling reason not to use URIs in this context.

**Comment by zimeon** [comment]
I agree that we should make these two definitions match. 

There is nothing in OCFL which requires identifiers to be URIs in order to work, so I lean toward merely recommending URIs. I note that there is also a distinction between identifiers that have URI syntax (`scheme:rest` -- not much restriction over arbitrary identifiers) and formally defined URI schemes with registered prefixes. For example, the DRUIDs used in Stanford's Moab have URI form (e.g. `druid:jq937jp0017`) but the prefix is not registered and such URIs should not be expected to be globally unique.
