### ISSUE TITLE
NAMASTE reference is a dead link

### ISSUE THREAD

**Issue by stevecassidy** [OCFL/spec#646]
The reference:

> [NAMASTE] Directory Description with Namaste Tags. J. Kunze.9 November 2009. URL: https://confluence.ucop.edu/download/attachments/14254149/NamasteSpec.pdf

is a dead link. A live version is available at:

https://ia801702.us.archive.org/2/items/ark_13030_c7g44hq41/NamasteSpec.pdf

but since this seems to be an abandoned standard perhaps it ought to be included here?  I can see other references to http://www.cdlib.org/inside/diglib/namaste/namastespec.html but that again is dead.

**Comment by rosy1280** [comment]
Thanks for pointing that out Steve.  I too noticed that on Friday and could have sworn we fixed that.  And then I realized I wasn't in the draft spec where the link is fixed: https://ocfl.io/draft/spec/#ref-namaste.

I'm going to close this since it should be updated in our next release.  I'll put on the editors agenda whether or not we can do some sort of point release to capture this and a handful of other minor edits.
